=== SignalK/specification/schemas/signalk.json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://signalk.github.io/specification/schemas/signalk.json#",
    "title": "SignalK",
    "description": "Root schema of Signal K. Contains the list of vessels plus a reference to the local boat (also contained in the vessels list).",
    "required": [ "vessels", "version" ],
    "properties": {
        "self": {
            "type": "string",
            "description": "This holds the key (UUID, MMSI or URL) of this vessel, the actual data is in the vessels array."
        },

        "vessels": {
            "type": "object",
            "description": "A wrapper object for vessel objects, each describing vessels in range, including this vessel.",
            "patternProperties": {
                "(^urn:mrn:(imo|signalk):(mmsi:[2-7][0-9]{8,8}|uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}))|^(http(s?):.*|mailto:.*|tel:(\\+?)[0-9]{4,})$": {
                    "description": "This regex pattern is used for validation of an MMSI or Signal K UUID identifier for the vessel. Examples: urn:mrn:imo:mmsi:230099999 urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
                    "$ref": "vessel.json#"
                }
            }
        },

        "sources": {
            "description": "Metadata about the data sources; physical interface, address, protocol, etc.",
            "$ref": "groups/sources.json#"
        },

        "resources": {
            "description": "Resources to aid in navigation and operation of the vessel including waypoints, routes, notes, etc.",
            "$ref": "groups/resources.json#"
        },

        "version": {
            "description": "Version of the schema and APIs that this data is using in Canonical format i.e. V1.0.0.",
            "$ref": "definitions.json#/definitions/version"
        }
    }
}

=== SignalK/specification/test/data/full-valid/ais-source.json
{
  "vessels": {
    "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d": {
      "uuid": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d"
    }
  },
  "sources": {
    "vhf": {
      "ais-b":{
        "ais":{
          "aisType": 15
        }
      },
      "label": "AIS-15.0",
      "type": "AIS"
    }
  },
  "version": "1.0.0",
  "self": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d"
}

=== SignalK/specification/samples/full/docs-data_model_multiple_values.json
{
  "self": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
  "version": "0.9.0",
  "vessels": {
    "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d": {
      "uuid": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
      "navigation": {
        "courseOverGroundTrue": {
          "value": 3.615624078431440,
          "$source": "ttyUSB0.GP",
          "timestamp": "2017-04-03T06:14:04.451Z",
          "values":{
            "ttyUSB0.GP.RMC":{
              "value": 3.615624078431440,
              "timestamp": "2017-04-03T06:14:04.451Z"
            },
            "n2k.ikommunicate.128267":{
              "value": 3.615624078431453,
              "timestamp": "2017-04-03T06:14:04.451Z"
            }
          }
        }
      }
    }
  },
  "sources":{
    "ttyUSB0": {
      "GP": {
        "sentences": {
          "RMC": "2017-04-03T06:14:04.451Z"
        }
      }
    },
    "ikommunicate": {
      "2": {
        "n2k": {
          "src": "2",
          "pgns": {
            "128267": "2017-04-03T06:14:05.221Z"
          }
        }
      }
    }
  }
}

=== SignalK/specification/test/data/lux.json
{
  "vessels": {
    "urn:mrn:imo:mmsi:230099999": {
      "mmsi": "230099999",
      "environment": {
        "outside": {
          "illuminance": {
            "value": 20000,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          }
        }
      }
    }
  },
  "sources": {
    "N2K-1": {
      "36": {
        "0": {},
        "n2k": {
          "src": "36",
          "pgns": {
            "130312": "2017-01-25T00:03:05.056Z"
          }
        }
      },
      "label": "",
      "type": "NMEA2000"
    }
  },
  "version": "1.0.0",
  "self": "vessels.urn:mrn:imo:mmsi:230099999"
}

=== SignalK/specification/test/data/full-valid/sources-sample.json
{
  "vessels": {
    "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d": {
      "uuid": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d"
    }
  },
  "sources": {
    "N2K-1": {
      "label": "N2K-1",
      "type": "NMEA2000",
      "36": {
        "n2k": {
          "src": "36",
          "pgns": {
            "130312": "2017-01-25T00:10:05.123Z"
          },
          "uniqueId": 1722191,
          "manufacturerId": 437,
          "deviceClass": 70,
          "deviceFunction": 140,
          "productID": 1739
        }
      },
      "manufacturerName": "Digital Yacht",
      "productName": "N2NET NMEA 2000 AIS",
      "softwareVersion": "040200.08.03.00",
      "hardwareVersion": "0",
      "serialNumber": "0000000",
      "installationNote1": "",
      "installationNote2": ""
    }
  },
  "version": "1.0.0",
  "self": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d"
}
